### ISSUE TITLE
[TASK]: GitHub Action - Add to task list

### ISSUE THREAD

**Issue by widal001** [widal001/project-demo#27]
## Summary

Create a GitHub action that automatically adds an issue to the task list of a parent ticket when an issue is added to the parent's corresponding milestone.

## To Do

- [ ] {Description of change 1}
- [ ] {Description of change 2}

## Definition of Done

- [ ] {Description of expected behavior once changes are made}
- [ ] {Description of expected behavior once changes are made}
